apiVersion: v1
kind: Service
metadata: 
  labels:
    pipeline: {{ .ObjectMeta.Name }} # facedetection-pipeline
    step: {{.Index}}  # steps[0] 对应第一阶段 facedetection-1
  name: {{ .Step.Model }} # facedetection-1
  namespace: pipeline # pipeline
spec: 
  selector:
    pipeline: {{ .ObjectMeta.Name }} # facedetection-pipeline
    step: {{.Index}}  # steps[0] 对应第一阶段
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort:  {{.Spec.ListenPort}}